### ISSUE TITLE
Clarify which Python versions are supported

### ISSUE THREAD

**Issue by csadorf** [Exabyte-io/esse#146]
Hello! Would it be possible to clarify which Python versions are supported? Thank you.

**Comment by triplepoint** [comment]
I believe all our Python code to date requires python 2.7, and not Python 3.  I've just done a quick review of the code in this repository, and in general it looks like it would make the jump to Python 3 pretty easily.  However, the import statements are still the ambiguous Python-2-style relative imports, and so in testing the code breaks in Python 3.

For now, I have a pull request out to be explicit in `setup.py` as to which versions of python are supported:
https://github.com/Exabyte-io/esse/pull/147

I expect some time soon there'll be a more comprehensive revision to address Python 3 compatibility.

I hope this helps.

**Comment by triplepoint** [comment]
Revisiting this, I think we've since addressed this ask.  I'm closing this as done, but please feel free to reopen it if you think this needs further attention.

Relevant changes:
- In the readme, we have a section stating the python version support https://github.com/Exabyte-io/esse/actions
- In the python setup.py, we have the `python_requires` field set to `>=3.6`, which should guide pip to finding the correct version.
